import '@/globals.css'

import { PlusJakartaSans } from '@/lib/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'App router practice',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={PlusJakartaSans.className}>{children}</body>
    </html>
  )
}
